<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="2012-20150403HL" name="case32-添加/取消订阅-查看订阅" tests="3" failures="1" timestamp="18 Sep 2015 05:48:04 GMT" time="117.063" errors="0">
  <testcase name="allinLogin" time="77.074" classname="com.allinmd.android.SubscribeEditCase"/>
  <testcase name="addSubscribe" time="8.179" classname="com.allinmd.android.SubscribeEditCase"/>
  <testcase name="checkSubscribe" time="6.152" classname="com.allinmd.android.SubscribeEditCase">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at message : expected [false] but found [true] in method : .checkSubscribe(SubscribeEditCase:94)
	at com.allinmd.android.SubscribeEditCase.checkSubscribe(SubscribeEditCase.java:94)
]]>
    </failure>
  </testcase> <!-- checkSubscribe -->
</testsuite> <!-- case32-添加/取消订阅-查看订阅 -->
