<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="2012-20150403HL" name="case02-手机注册-跳过认证" tests="2" failures="1" timestamp="17 Sep 2015 05:53:32 GMT" time="49.796" errors="0">
  <testcase name="assertRegButton" time="6.518" classname="com.allinmd.android.RegPhoneCase"/>
  <testcase name="regPhone" time="17.971" classname="com.allinmd.android.RegPhoneCase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.allinmd.util.GetResetPasswd.resGetPhone(GetResetPasswd.java:57)
	at com.allinmd.util.GetResetPasswd.getPhoneCode(GetResetPasswd.java:130)
	at com.allinmd.po.androiddriver.RegPageElements.regPhoneFlow(RegPageElements.java:112)
	at com.allinmd.android.RegPhoneCase.regPhone(RegPhoneCase.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- regPhone -->
</testsuite> <!-- case02-手机注册-跳过认证 -->
